// <auto-generated />
using System;
using AirsoftLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirsoftLogger.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210403133746_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirsoftLogger.Models.Address", b =>
                {
                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Postcode");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AirsoftLogger.Models.Events", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FKSITESiteCode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Type")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Date");

                    b.HasIndex("FKSITESiteCode");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AirsoftLogger.Models.Site", b =>
                {
                    b.Property<string>("SiteCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Tel")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteCode");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("AirsoftLogger.Models.Events", b =>
                {
                    b.HasOne("AirsoftLogger.Models.Site", "FKSITE")
                        .WithMany()
                        .HasForeignKey("FKSITESiteCode");

                    b.Navigation("FKSITE");
                });
#pragma warning restore 612, 618
        }
    }
}
