INSERT INTO dbo.Addresses Values ('KT111NH',	'Old Lane',	'Surrey')
INSERT INTO dbo.Addresses VALUES ('DH61QQ',	'Elemore Ln',	'Durham')
INSERT INTO dbo.Addresses VALUES ('DN327AJ',	'Freeman St',	'Grimsby')
INSERT INTO dbo.Addresses VALUES ('TN127DG',	'Old Hay',	'Brenchley')
INSERT INTO dbo.Addresses VALUES ('CO77US',	'Hilliards Rd',	'Colchester')
INSERT INTO dbo.Addresses VALUES ('RG47TR',	'Mapledurham Dr',	'Reading')
INSERT INTO dbo.Addresses VALUES ('NG323PY',	'Wood Lodge',	'Grantham')
INSERT INTO dbo.Addresses VALUES ('SO322HL',	'Botley Rd',	'Southampton')
INSERT INTO dbo.Addresses VALUES ('IV519EG',	'Struan Rd',	'Portree')
INSERT INTO dbo.Addresses VALUES ('CM210LT',	'Parsonage Lane',	'Sawbridgeworth')
INSERT INTO dbo.Addresses VALUES ('AB315HP',	'Druggam',	'Banchory')
INSERT INTO dbo.Addresses VALUES ('PE282LR',	'Monks Wood Paintball Park',	'Huntingdon')
INSERT INTO dbo.Addresses VALUES ('NR162TH',	'Roudham Heath',	'Norfolk')
INSERT INTO dbo.Addresses VALUES ('LE93GQ',	'Winston Ave',	'Leicester')
INSERT INTO dbo.Addresses VALUES ('RH54RW',	'Henfold Ln',	'Dorking')
INSERT INTO dbo.Addresses VALUES ('ST138TL',	'Blackshaw Moor',	'Leek')
INSERT INTO dbo.Addresses VALUES ('BH242DF',	'Ashley Dr',	'Ringwood')
INSERT INTO dbo.Addresses VALUES ('DN186RA',	'Leggotts Quarry',	'Barton-upon-Humber')
INSERT INTO dbo.Addresses VALUES ('HD75QG',	'Colne Valley Business Park',	'Huddersfield')
INSERT INTO dbo.Addresses VALUES ('LS101LS',	'Sayner Ln',	'Leeds')
INSERT INTO dbo.Addresses VALUES ('EH234SB',	'Allanshaw Wood',	'Gorebridge')
INSERT INTO dbo.Addresses VALUES ('OX171LZ',	'Culworth Rd',	'Banbury')
INSERT INTO dbo.Addresses VALUES ('ML75AB',	'Dura Rd',	'Shotts')
INSERT INTO dbo.Addresses VALUES ('BS153BT',	'Brockley Combe Rd',	'Bristol')
INSERT INTO dbo.Addresses VALUES ('MK437AE',	'Dungee Road',	'Northampton')
INSERT INTO dbo.Addresses VALUES ('PO139UG',	'Browndown Rd',	'Lee-on-the-Solent')
INSERT INTO dbo.Addresses VALUES ('NG229FG',	'Ollerton Rd',	'Newark')
INSERT INTO dbo.Addresses VALUES ('NR161HQ',	'Traice Rd',	'Norwich')
INSERT INTO dbo.Addresses VALUES ('HP143NP',	'Fryers Farm Lane',	'High Wycombe')
INSERT INTO dbo.Addresses VALUES('KY26QZ',	'Strathore Rd',	'Kirkcaldy')
INSERT INTO dbo.Addresses VALUES('LE157TU',	'Ashwell Rd',	'Oakham')
INSERT INTO dbo.Addresses VALUES('SE78NJ',	'Herringham Rd',	'London')
INSERT INTO dbo.Addresses VALUES('ST104JT',	'Hollington Rd',	'Stoke-on-Trent')
INSERT INTO dbo.Addresses VALUES('S728RE',	'Engine Ln',	'Barnsley')
